// Code generated by MockGen. DO NOT EDIT.
// Source: redis_repo.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/oyamo/wallet-api/internal/models"
)

// MockRedisRepository is a mock of RedisRepository interface.
type MockRedisRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRedisRepositoryMockRecorder
}

// MockRedisRepositoryMockRecorder is the mock recorder for MockRedisRepository.
type MockRedisRepositoryMockRecorder struct {
	mock *MockRedisRepository
}

// NewMockRedisRepository creates a new mock instance.
func NewMockRedisRepository(ctrl *gomock.Controller) *MockRedisRepository {
	mock := &MockRedisRepository{ctrl: ctrl}
	mock.recorder = &MockRedisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisRepository) EXPECT() *MockRedisRepositoryMockRecorder {
	return m.recorder
}

// DeleteWalletCtx mocks base method.
func (m *MockRedisRepository) DeleteWalletCtx(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWalletCtx", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWalletCtx indicates an expected call of DeleteWalletCtx.
func (mr *MockRedisRepositoryMockRecorder) DeleteWalletCtx(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWalletCtx", reflect.TypeOf((*MockRedisRepository)(nil).DeleteWalletCtx), ctx, key)
}

// GetByIDCtx mocks base method.
func (m *MockRedisRepository) GetByIDCtx(ctx context.Context, key string) (*models.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDCtx", ctx, key)
	ret0, _ := ret[0].(*models.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDCtx indicates an expected call of GetByIDCtx.
func (mr *MockRedisRepositoryMockRecorder) GetByIDCtx(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDCtx", reflect.TypeOf((*MockRedisRepository)(nil).GetByIDCtx), ctx, key)
}

// SetWalletCtx mocks base method.
func (m *MockRedisRepository) SetWalletCtx(ctx context.Context, key string, seconds int, user *models.Wallet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWalletCtx", ctx, key, seconds, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWalletCtx indicates an expected call of SetWalletCtx.
func (mr *MockRedisRepositoryMockRecorder) SetWalletCtx(ctx, key, seconds, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWalletCtx", reflect.TypeOf((*MockRedisRepository)(nil).SetWalletCtx), ctx, key, seconds, user)
}
